;;;; package.lisp

(defpackage #:sel
  (:use #:cl
        #:drakma)
  (:local-nicknames (:a :alexandria))
  (:export
   #:with-session
   #:make-session
   #:server-status
   #:get-url
   #:go-to
   #:get-timeouts
   #:set-timeouts
   #:back
   #:forward
   #:refresh
   #:get-active-element
   #:get-title
   #:get-window-handle
   #:get-window-handles
   #:get-window-rect
   #:set-window-rect
   #:maximize-window
   #:minimize-window
   #:fullscreen-window
   #:switch-to-window
   #:new-window
   #:switch-to-frame
   #:switch-to-parent-frame
   #:find-element
   #:find-elements
   #:from-element
   #:elements-from-element
   #:click
   #:clear
   #:type-text
   #:element-selected-p
   #:get-element-attribute
   #:get-element-property
   #:get-element-css-value
   #:get-element-text
   #:get-element-tag-name
   #:get-element-rect
   #:element-enabled-p
   #:get-page-source
   #:get-cookies
   #:get-cookie
   #:dismiss-alert
   #:accept-alert
   #:send-alert-text
   #:get-alert-text
   #:print-page
   #:take-screenshot
   #:take-element-screenshot
   #:destroy
   #:elements-from-element-by-xpath
   #:elements-from-element-by-tag-name
   #:elements-from-element-by-partial-link-text
   #:elements-from-element-by-link-text
   #:elements-from-element-by-css-selector
   #:from-element-by-css-selector
   #:from-element-by-link-text
   #:from-element-by-partial-link-text
   #:from-element-by-tag-name
   #:from-element-by-xpath
   #:find-elements-by-css-selector
   #:find-elements-by-link-text
   #:find-elements-by-partial-link-text
   #:find-elements-by-tag-name
   #:find-elements-by-xpath
   #:find-element-by-css-selector
   #:find-element-by-link-text
   #:find-element-by-partial-link-text
   #:find-element-by-tag-name
   #:find-element-by-xpath
   #:set-script-timeout
   #:set-page-load-timeout
   #:set-implicit-timeout
   #:set-width
   #:set-height
   #:set-x
   #:set-y))
