(with-session (sess)
  (go-to sess :url "https://reddit.com")
  (take-screenshot sess "~/test-image")
  (let ((active-element (get-active-element sess)))
    (take-element-screenshot sess active-element)))
